#!/usr/bin/env bash
set -euo pipefail

# Prompt Manager — Desktop Integration Installer
# Supports: KDE Plasma (Wayland/X11), GNOME, and any FreeDesktop-compliant DE.
# Idempotent: safe to re-run after `git pull`, theme/template/github updates.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

echo "=== Installing Prompt Manager Desktop Application ==="
echo "Repository path: ${REPO_DIR}"
echo "App version:     $(grep -m1 '^version' "${REPO_DIR}/pyproject.toml" | sed 's/.*\"\(.*\)\".*/\1/')"
echo ""

# ── XDG paths ────────────────────────────────────────────────────────
BIN_DIR="${HOME}/.local/bin"
APPS_DIR="${HOME}/.local/share/applications"
ICONS_DIR="${HOME}/.local/share/icons/hicolor/scalable/apps"
PIXMAPS_DIR="${HOME}/.local/share/pixmaps"

mkdir -p "${BIN_DIR}" "${APPS_DIR}" "${ICONS_DIR}" "${PIXMAPS_DIR}"

# ── Detect Python & check deps ───────────────────────────────────────
PYTHON_BIN="${PYTHON:-/usr/bin/python3}"
if ! command -v "${PYTHON_BIN}" >/dev/null 2>&1; then
    echo "ERROR: ${PYTHON_BIN} not found. Install Python 3.10+."
    exit 1
fi
echo "Using Python: ${PYTHON_BIN} ($(${PYTHON_BIN} --version))"

# Ensure PyQt6 is importable (either system package or venv/pip)
if ! "${PYTHON_BIN}" -c "import PyQt6" 2>/dev/null; then
    echo ""
    echo "⚠ PyQt6 not found for ${PYTHON_BIN}."
    echo "  Install it via your distro package manager or pip:"
    echo "    pip install --user PyQt6>=6.4.0"
    echo "    # or Debian/Ubuntu: sudo apt install python3-pyqt6"
    echo "    # or Fedora:       sudo dnf install python3-qt6"
    echo ""
    read -r -p "Attempt 'pip install --user -e .'? [y/N] " _ans
    if [[ "${_ans:-}" =~ ^[Yy]$ ]]; then
        "${PYTHON_BIN}" -m pip install --user -e "${REPO_DIR}"
    else
        echo "Aborting. Install PyQt6 then re-run ./desktop/install.sh"
        exit 1
    fi
fi

# Prefer an editable pip install if the repo is a checkout (keeps wrapper simple)
# but fall back to PYTHONPATH wrapper so `git pull` is reflected instantly.
PIP_EDITABLE_MARKER="${REPO_DIR}/.pip-installed"
if "${PYTHON_BIN}" -m pip show prompt-manager >/dev/null 2>&1; then
    echo "✓ prompt-manager already pip-installed ($(${PYTHON_BIN} -m pip show prompt-manager | grep -m1 Version))."
    echo "  Ensuring it is up-to-date..."
    # Refresh editable install so new modules (github_client, template_manager, themes) are seen
    if [[ -f "${REPO_DIR}/pyproject.toml" ]]; then
        "${PYTHON_BIN}" -m pip install --user -e "${REPO_DIR}" --quiet 2>&1 | tail -n 5 || true
        touch "${PIP_EDITABLE_MARKER}"
    fi
else
    echo "pip package not yet installed — will use PYTHONPATH wrapper (dev mode)."
    echo "Tip: for a proper install run:  pip install --user -e ."
fi

# ── 1. Launcher wrapper ~/.local/bin/prompt-manager ──────────────────
LAUNCHER="${BIN_DIR}/prompt-manager"
echo ""
echo "Creating launcher wrapper at: ${LAUNCHER}"
cat > "${LAUNCHER}" <<EOF
#!/usr/bin/env bash
# Generated by Prompt Manager desktop/install.sh — do not edit manually.
# Prefers pip-installed entry point, falls back to repo checkout.

# Wayland/X11 auto-detection (preserved for KDE Plasma)
export QT_QPA_PLATFORM="\${QT_QPA_PLATFORM:-wayland;xcb}"
export QT_AUTO_SCREEN_SCALE_FACTOR="\${QT_AUTO_SCREEN_SCALE_FACTOR:-1}"

# If pip-installed, use the entry point directly (fastest)
if command -v prompt-manager.orig >/dev/null 2>&1; then
    exec prompt-manager.orig "\$@"
fi

# Fallback: run from repo checkout via PYTHONPATH (reflects git pull instantly)
export PYTHONPATH="${REPO_DIR}:\$PYTHONPATH"
exec "${PYTHON_BIN}" -m prompt_manager.app "\$@"
EOF
chmod +x "${LAUNCHER}"

# If pip entry point exists, keep it as prompt-manager.orig for the wrapper to delegate
if "${PYTHON_BIN}" -m pip show prompt-manager >/dev/null 2>&1; then
    PIP_BIN="$(python3 -c 'import sysconfig, pathlib; print(pathlib.Path(sysconfig.get_path(\"scripts\")) / \"prompt-manager\")')"
    # Common user base bin is ~/.local/bin — wrapper already occupies that name, so stash original
    if [[ -f "${PIP_BIN}" && "${PIP_BIN}" != "${LAUNCHER}" ]]; then
        cp -f "${PIP_BIN}" "${BIN_DIR}/prompt-manager.orig" 2>/dev/null || true
    fi
fi

if [[ ":${PATH}:" != *":${BIN_DIR}:"* ]]; then
    echo "⚠ ${BIN_DIR} is not on your PATH. Add to ~/.bashrc / ~/.zshrc:"
    echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

# ── 2. Icons ─────────────────────────────────────────────────────────
ICON_SRC="${REPO_DIR}/prompt_manager/ui/assets/icon.svg"
ICON_DEST="${ICONS_DIR}/prompt-manager.svg"
echo ""
echo "Installing application icon to: ${ICON_DEST}"
if [[ -f "${ICON_SRC}" ]]; then
    cp -f "${ICON_SRC}" "${ICON_DEST}"
    cp -f "${ICON_SRC}" "${PIXMAPS_DIR}/prompt-manager.svg"
    # Optional: render PNG fallbacks at common sizes if rsvg-convert is available
    if command -v rsvg-convert >/dev/null 2>&1; then
        for sz in 16 24 32 48 64 128 256; do
            PNG_DIR="${HOME}/.local/share/icons/hicolor/${sz}x${sz}/apps"
            mkdir -p "${PNG_DIR}"
            rsvg-convert -w "${sz}" -h "${sz}" "${ICON_SRC}" -o "${PNG_DIR}/prompt-manager.png" 2>/dev/null || true
        done
        echo "  (also rendered PNG fallbacks for legacy trays)"
    fi
else
    echo "⚠ Icon source not found: ${ICON_SRC}"
fi

# ── 3. Desktop entry ─────────────────────────────────────────────────
DESKTOP_SRC="${SCRIPT_DIR}/prompt-manager.desktop"
DESKTOP_DEST="${APPS_DIR}/prompt-manager.desktop"
echo ""
echo "Installing desktop entry to: ${DESKTOP_DEST}"
# Substitute absolute Exec path (Flatpak/pip wrappers use launcher)
sed -e "s|^Exec=prompt-manager|Exec=${LAUNCHER}|g" \
    -e "s|^Exec=prompt-manager --new|Exec=${LAUNCHER} --new|g" \
    -e "s|^Exec=prompt-manager --new-template|Exec=${LAUNCHER} --new-template|g" \
    -e "s|^Exec=prompt-manager --manage-templates|Exec=${LAUNCHER} --manage-templates|g" \
    -e "s|^Exec=prompt-manager --github-push|Exec=${LAUNCHER} --github-push|g" \
    -e "s|^Exec=prompt-manager --github-pull|Exec=${LAUNCHER} --github-pull|g" \
    "${DESKTOP_SRC}" > "${DESKTOP_DEST}"
chmod +x "${DESKTOP_DEST}"

# ── 4. Refresh caches ────────────────────────────────────────────────
echo ""
if command -v update-desktop-database >/dev/null 2>&1; then
    echo "Updating desktop database..."
    update-desktop-database "${APPS_DIR}" 2>/dev/null || true
fi
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    echo "Updating GTK icon cache..."
    gtk-update-icon-cache -f -t "${HOME}/.local/share/icons/hicolor" 2>/dev/null || true
fi
if command -v kbuildsycoca6 >/dev/null 2>&1; then
    echo "Updating KDE service cache (kbuildsycoca6)..."
    kbuildsycoca6 2>/dev/null || true
elif command -v kbuildsycoca5 >/dev/null 2>&1; then
    echo "Updating KDE service cache (kbuildsycoca5)..."
    kbuildsycoca5 2>/dev/null || true
fi

# ── 5. Validate ──────────────────────────────────────────────────────
echo ""
if command -v desktop-file-validate >/dev/null 2>&1; then
    echo "Validating desktop file syntax..."
    if desktop-file-validate "${DESKTOP_DEST}"; then
        echo "✓ Desktop file is valid."
    else
        echo "⚠ desktop-file-validate reported warnings (see above) — still installable."
    fi
else
    echo "(desktop-file-validate not installed — skipping syntax check)"
fi

# Quick sanity: can the module be imported?
if ! "${PYTHON_BIN}" -c "import prompt_manager; import prompt_manager.ui.main_window; import prompt_manager.storage.database; print('  import check: OK')" 2>&1; then
    echo "⚠ Import check failed — run: ${PYTHON_BIN} -c 'import prompt_manager' to diagnose."
fi

echo ""
echo "======================================================="
echo " Prompt Manager successfully installed!"
echo "  • App launcher:  KDE Kickoff / GNOME Overview → Prompt Manager"
echo "  • KRunner:       Alt+Space → 'Prompt Manager' or 'prompt-manager'"
echo "  • Terminal:      prompt-manager [--new] [--manage-templates] [--help]"
echo "  • Quick Actions: Right-click icon → New Prompt / New Template / Manage Templates / GitHub Push/Pull"
echo "  • Themes:        13 themes via View → Theme (Ctrl+T toggle)"
echo "  • Templates:     Templates → Manage Templates (Ctrl+Shift+T, starts empty)"
echo "  • GitHub Sync:   GitHub → Connect / Manage (OAuth or PAT)"
echo "======================================================="
echo ""
echo "To uninstall:  ./desktop/uninstall.sh"
